name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: tx-uml/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: tx-uml

    - name: Build
      run: npm run build
      working-directory: tx-uml

    # - name: Test
    #   run: npm test
    #   working-directory: tx-uml
